spring:
  mongodb:
    embedded:
      version: 3.0.0

  webflux:
    hiddenmethod:
      filter:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 494765666736-jchcrc7po8sts2efqr3rrlbtfaubq48i.apps.googleusercontent.com
            client-secret: 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

logging:
  level:
    web: DEBUG

management:
  endpoint:
    health:
      show-details: always

info:
  project:
    version: @project.version@
  java:
    version: @java.version@
  spring:
    framework:
      version: @spring-framework.version@
    data:
      versioin: @spring-data-bom.version@
